<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class LearningTestQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sourceImagesPath = database_path('seeders/data/learning_tests');

        $imageInfo = [
            [
                'question_id' => 16,
                'image_name' => '01J3ZY7PD2HTKNQS8HT4XVWTP9.jpg',
                'image_path' => null,
            ]
        ];

        for ($i = 0; $i < count($imageInfo); $i++) {
            if (!Storage::disk('public')->exists("learning_questions/{$imageInfo[$i]['question_id']}")) {
                Storage::disk('public')->makeDirectory("learning_questions/{$imageInfo[$i]['question_id']}");
            }

            $existingImages = Storage::disk('public')->files("learning_questions/{$imageInfo[$i]['question_id']}");
            if (count($existingImages) < 1) {
                // Read the content of the image file
                $image = File::get("$sourceImagesPath/{$imageInfo[$i]['image_name']}");

                $imageExtension = pathinfo($imageInfo[$i]['image_name'], PATHINFO_EXTENSION);

                $imageExtension = !empty($imageExtension) ? $imageExtension : 'png';

                $imageName = strtoupper(Str::random(26)) . '.' . $imageExtension;

                $imagePath = "learning_questions/{$imageInfo[$i]['question_id']}/$imageName";
                $imageInfo[$i]['image_path'] = $imagePath;

                // Store the content in the correct folder
                Storage::disk('public')->put($imagePath, $image);
            } else {
                $imageInfo[$i]['image_path'] = $existingImages[0];
            }
        }

        $questions = [
            [
                'test_id' => 1,
                'is_active' => 1,
                'question_title' => 'Kādi faktori jāņem vērā, izvēloties augus apstādījumiem?',
                'question_description' => 'Šis jautājums pārbauda, vai zināt, kā izvēlēties augus, kas vislabāk atbilst konkrētajam klimatam un augsnes tipam.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => $imageInfo[0]['image_path'],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 1,
                'is_active' => 1,
                'question_title' => 'Kā izvēlēties piemērotus augus sezonālai apzaļumošanai?',
                'question_description' => '',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 1,
                'is_active' => 1,
                'question_title' => 'Kad ir vislabāk stādīt ziemciešu augus?',
                'question_description' => 'Noskaidro, kurā sezonā ir optimāli stādīt ziemciešu augus, lai tie veiksmīgi iesakņotos un attīstītos.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 1,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādā gadalaikā parasti notiek pavasara mēslošana?',
                'question_description' => 'Šis jautājums pārbauda, vai zināt par optimālo laiku pavasara mēslošanai, kas palīdz uzlabot augsnes kvalitāti.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 1,
                'is_active' => rand(0, 1),
                'question_title' => 'Kāds ir galvenais iemesls, kāpēc augiem var trūkt ūdens?',
                'question_description' => '',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 1,
                'is_active' => rand(0, 1),
                'question_title' => 'Kāds ir visbiežākais augu barības vielu trūkuma simptoms?',
                'question_description' => 'Noskaidro, kāds ir biežākais simptoms, kas liecina par augu barības vielu trūkumu, kas var ietekmēt to augšanu un attīstību.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 2,
                'is_active' => 1,
                'question_title' => 'Kādi ir galvenie faktori, plānojot estētisku un funkcionālu dārza dizainu?',
                'question_description' => 'Šis jautājums pārbauda, vai saprotat, kādi faktori ir svarīgi, lai izveidotu dārza dizainu, kas ir gan estētisks, gan praktisks.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 2,
                'is_active' => rand(0, 1),
                'question_title' => 'Kāds ir labākais veids, kā izvietot āra apgaismojumu, lai izceltu dārza elementus?',
                'question_description' => 'Noskaidro, kā vislabāk izvietot āra apgaismojumu, lai uzsvērtu dārza elementus un radītu vēlamo atmosfēru.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 2,
                'is_active' => 1,
                'question_title' => 'Kādus ūdens elementus var iekļaut dārza labiekārtošanā?',
                'question_description' => 'Uzzini, kādi ūdens elementi, piemēram, strūklakas vai dīķi, var papildināt dārza dizainu.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 2,
                'is_active' => 1,
                'question_title' => 'Kādas ir galvenās pieejas ūdens elementu ierīkošanai dārzā?',
                'question_description' => 'Šis jautājums pārbauda, vai zināt galvenās pieejas, kā ierīkot ūdens elementus, piemēram, dīķus vai strūklakas.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 2,
                'is_active' => rand(0, 1),
                'question_title' => 'Kā izvēlēties pareizo āra apgaismojumu, lai izceltu ainavas elementus?',
                'question_description' => 'Noskaidro, kā izvēlēties piemērotu āra apgaismojumu, kas palīdzēs izcelt ainavas elementus un radīt vēlamo efektu.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 2,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādi ir galvenie aspekti, lai izveidotu funkcionālu dārza dizainu?',
                'question_description' => 'Šis jautājums palīdz noteikt, vai saprotat, kādi aspekti ir svarīgi, lai izveidotu funkcionālu un lietderīgu dārza dizainu.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 3,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādas ir galvenās sastāvdaļas veiksmīgā projekta plānošanā?',
                'question_description' => 'Šis jautājums pārbauda, vai zināt, kādi ir būtiskie faktori, lai izveidotu veiksmīgu projektu no plānošanas perspektīvas.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 3,
                'is_active' => 1,
                'question_title' => 'Kā nodrošināt efektīvu komunikāciju projekta laikā?',
                'question_description' => 'Noskaidro, kādas ir labākās prakses, lai uzturētu skaidru un efektīvu komunikāciju starp projekta dalībniekiem.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 3,
                'is_active' => 1,
                'question_title' => 'Kādas ir ilgtspējīgas prakses ainavu būvniecībā?',
                'question_description' => 'Šis jautājums palīdz noteikt, vai saprotat, kādas prakses var veicināt ilgtspējīgus rezultātus ainavu būvniecības projektos.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 3,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādas ir galvenās risku pārvaldības stratēģijas projektu vadībā?',
                'question_description' => 'Noskaidro, kādi ir galvenie veidi, kā identificēt un pārvaldīt riskus, kas var ietekmēt projekta gaitu.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 3,
                'is_active' => rand(0, 1),
                'question_title' => 'Kā pārvaldīt budžetu projekta vadībā?',
                'question_description' => 'Uzzini, kādas ir labākās prakses, lai plānotu un uzraudzītu projekta budžetu efektīvi.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 3,
                'is_active' => 1,
                'question_title' => 'Kā nodrošināt projektu atbilstību kvalitātes standartiem?',
                'question_description' => 'Noskaidro, kādi pasākumi ir jāveic, lai nodrošinātu, ka projekta rezultāti atbilst noteiktajiem kvalitātes standartiem.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 4,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādi ir galvenie drošības aprīkojuma elementi būvniecībā?',
                'question_description' => 'Šis jautājums pārbauda, vai zināt, kāds aprīkojums ir nepieciešams, lai nodrošinātu drošību būvniecības vietā.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 4,
                'is_active' => 1,
                'question_title' => 'Kāds ir pareizais veids, kā uzglabāt bīstamas vielas būvniecībā?',
                'question_description' => 'Noskaidro, kā jāuzglabā bīstamas vielas, lai nodrošinātu drošību darba vietā.',
                'answer_type' => 'text',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 4,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādi ir galvenie aspekti, izvēloties atbilstošu darba tehniku?',
                'question_description' => 'Šis jautājums palīdz noteikt, vai zināt, kā izvēlēties piemērotu tehniku, lai veiktu būvniecības darbus efektīvi un droši.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 4,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādas ir regulāras tehnikas apkopšanas darbības?',
                'question_description' => 'Noskaidro, kādas darbības ir nepieciešamas, lai regulāri apkoptu un uzturētu tehniku labā darba kārtībā.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 4,
                'is_active' => 1,
                'question_title' => 'Kāds ir galvenais mērķis darba vietas risku novērtēšanai?',
                'question_description' => 'Šis jautājums palīdz saprast, kāda ir risku novērtēšanas nozīme darba vietā, lai novērstu negadījumus un traumas.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 4,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādi ir galvenie personiskās aizsardzības līdzekļi būvniecībā?',
                'question_description' => 'Noskaidro, kādi personiskās aizsardzības līdzekļi ir jāizmanto, lai nodrošinātu drošību būvniecības darbā.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => rand(0, 1),
                'question_title' => 'Kas ir stipras paroles pamatnoteikums?',
                'question_description' => 'Izvēlies galveno faktoru, kas padara paroli drošu.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => rand(0, 1),
                'question_title' => 'Kas ir phishing uzbrukums?',
                'question_description' => 'Noskaidro, kas tiek saprasts ar terminu "phishing".',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => rand(0, 1),
                'question_title' => 'Kāpēc ir svarīgi atjaunināt programmatūru?',
                'question_description' => 'Izvēlies pareizo iemeslu, kāpēc regulāri jāatjaunina programmas un operētājsistēmas.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => rand(0, 1),
                'question_title' => 'Vai vienmēr vajadzētu izmantot antivīrusu programmu?',
                'question_description' => 'Noskaidro, vai vienmēr ir nepieciešams izmantot antivīrusu programmu, lai aizsargātu datoru.',
                'answer_type' => 'text',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => rand(0, 1),
                'question_title' => 'Kādu informāciju nevajadzētu dalīties sociālajos tīklos?',
                'question_description' => 'Izvēlies informāciju, kas nekad nevajadzētu publiski izpaust sociālajos tīklos.',
                'answer_type' => 'select_option',
                'points' => rand(1, 5),
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => 1,
                'question_title' => 'Kas ir drošākais interneta savienojums?',
                'question_description' => 'Izvēlies pareizo aprakstu, kas raksturo drošu interneta savienojumu.',
                'answer_type' => 'select_option',
                'points' => 2,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 5,
                'is_active' => 1,
                'question_title' => 'Kā nevajag rīkoties, ja saņemat aizdomīgu e-pastu?',
                'question_description' => 'Izvēlies pareizo rīcību, kad saņemat aizdomīgu e-pastu no nezināma sūtītāja.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs √361?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs reizinot 7 x 8?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs dalot 144 ar 12?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs saskaitot 45 + 23?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Kāds ir kvadrātsakne no 625?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs 3^4 (3 ceturtajā pakāpē)?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs 15% no 200?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs 2^5 + 3^3?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs 5! (5 faktoriāls)?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'test_id' => 6,
                'is_active' => 1,
                'question_title' => 'Cik būs 7^2 - 4^3?',
                'question_description' => 'Izvēlies pareizo atbildi.',
                'answer_type' => 'select_option',
                'points' => 1,
                'visual_content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('learning_test_questions')->insert($questions);
    }
}
